export const ENABLE_USE_TRANSITION = "settings/ENABLE_USE_TRANSITION";
export const ENABLE_PENDING_DELAY = "settings/ENABLE_PENDING_DELAY";
export const TRANSTION_TIME = "settings/TRANSTION_TIME";
export const SUPERHEROES_DELAY = "settings/SUPERHEROES_DELAY";
export const SUPERPOWERS_DELAY = "settings/SUPERPOWERS_DELAY";
